ovh/overthebox-feeds

luci-app-overthebox/luasrc/view/overthebox/index.htm

After a long time spent on the dashboard, the browser crash

bugfix: avoid crash after a long time spent on dashboard

---

README.md

Glorytun doesn't require AESNI any more.

AESNI is not required any more

---

mwan3otb/files/usr/sbin/track.lua

ping and nslookup recvfrom function can exit on signal causing EAGAIN (11) error
In this case a new recvfrom call is required to resume.
As track on ICMP is now used by TUN and XTUN this fix is required.
add test for incoming ECHO request

fix for satellite (con't)

---

overthebox/files/usr/lib/lua/overthebox.lua

Bug occurring when tprint is called with a string instead of a table

Bug in tprint function (overthebox.lua)

---

overthebox/files/usr/bin/overtheboxd

When upgrade action was launched, if opkg update failed, the action was returned as succeeded even though a part of it failed.

Return an error when opkg update fails during upgrade.

---

glorytun-udp/Makefile
glorytun-udp/files/glorytun.sh

This commit adds MTU negotiation and fixes the 'trap invalid opcode' issue.

Update glorytun-udp to 0.0.67-mud

---

mwan3otb/files/usr/sbin/track.lua

We have to seed only one time and dns id is an unsigned short integer.

Fix random id for dns in track.lua

---

dnsmasq/Makefile
dnsmasq/patches/420-servfail.patch

When dnsmasq is forwarding, we don't want SERVFAIL responses coming from upstream to be forwarded to the client if we have other upstreams which are working properly.

dnsmasq: Consider SERVFAIL as a non-successful response

---

bandwidth/Makefile
bandwidth/files/bandwidth

Fix race condition occurring when several OTB apps use iptables at the same time.
> Another app is currently holding the xtables lock; waiting for it to exit...
http://git.netfilter.org/iptables/commit/?h=v1.4.20&id=93587a04d0f2511e108bbc4d87a8b9d28a5c5dd8

bandwidth: Fix xtables lock error

---

overthebox/files/etc/sysctl.d/shadowsocks.conf

The 120s tcp_timeout_established of commit b0f09f7 has way too many
side-effects.

Do not throttle tcp_timeout_established down

---

dnsmasq/Makefile
overthebox/Makefile
overthebox/files/usr/lib/lua/overthebox.lua

dnsmasq-full is a "VARIANT" (using openWRT Makefile terminology) of
dnsmasq. This means they share most of their files, because dnsmasq-full
just enables more features than dnsmasq does.
dnsmasq and dnsmasq-full were both installed. #a7a4abb changed a
dependency in package overthebox from "dnsmasq" to "dnsmasq-full". This
is because we only need dnsmasq-full. But by doing so, dnsmasq was
automatically removed. This happens because dnsmasq was auto-installed
(install triggered by a dependency satisfaction) and no package depend
on it any more.  If dnsmasq had been installed after dnsmasq-full, it
was considered to be the one which triggered the files installation (see
file /usr/lib/opkg/info/dnsmasq.list). And in that case, when dnsmasq is
auto-removed, the files vanish together with it, …

Put an end to the dnsmasq/dnsmasq-full battle

---

luci-app-overthebox/Makefile
luci-base/Makefile
luci-mod-admin-full/Makefile

luci-app-overthebox, luci-base and luci-mod-admin-full were upgraded at
each OTB upgrade, even if those packets were already up-to-date. This is
because by default, if PKG_VERSION is not set, luci generates a
PKG_VERSION using the git commit sha1 and the date. This caused the
version number to change all the time, triggering useless upgrades each
time.
https://github.com/ovh/overthebox-feeds/blob/master/luci/luci.mk#L61

Prevent luci apps from being upgraded all the time

---

overthebox/Makefile
overthebox/defaults/uhttpd.defaults

With only HTTPS allowed, the first connexion might be really painful
with warnings and alerts made by the browser about the 'non-safe'
certificate (the one that is self signed certificate by OpenWRT on the
OTB)
Signed-off-by: Lucas BEE <pouulet@gmail.com>

[WIP] Allow HTTP and HTTPS for accessing the interface

---

overthebox/defaults/uhttpd.defaults

If we don't commit the change it will appear as an unsaved change
It fixes the bug introduced by #221

Fix missing uci commit in uhttpd defaults

---

overthebox/defaults/dnsmasq.defaults

Disable all IPv6 values by default.
These values are in conflict with the fact that IPv6 is not yet
implemented in OTB and can create navigation issues
These values were deleted in 1b917427ab by mistake

Set default dnsmasq values about IPv6

---

overthebox/files/usr/lib/lua/overthebox.lua

- remove restart of not dependant services as network and firewall (which is reloaded by mwan3 himself)
- use reload_config helper to restart mwan3 only when the mwan3 config has changed, should correct a possible race condition reload.

Fix mwan3 reload behaviour

---

shadowsocks-libev/files/shadowsocks.hotplug
shadowsocks-libev/files/shadowsocks.init

- Use ipset to allow seamless reload and cleaner iptables rules.
- Set hook on all interfaces in LAN zone.
- Update hotplug script to include interface address when goes up (reload).

Shadowsocks: Improve iptables rules with ipset and add hook on lan zone interfaces

---

mwan3otb/files/usr/sbin/track.lua

Fix the error : 
`daemon.err mwan3track[2194]: lua: /usr/sbin/mwan3track:1042: bad argument #4 to 'format' (string expected, got nil)`

Fix mwan3 bad nil check

---

netifd/files/lib/netifd/proto/ptp.sh

It was awening with errors saying :
tun0 (8749): ./ptp.sh: eval: line 1: proto_ptp_teardown: not found

Bring back teardown PTP

---

shadowsocks-libev/Makefile
shadowsocks-libev/files/shadowsocks.init

In the ss-redir init script, we fill the iptables chain "socks_hook"
with one rule per interface belonging to the zone "lan".
Sometimes, the syntax used in the uci configuration is:
```
list network 'lan1'
list network 'lan2'
```
whereas sometimes, it's:
```option network 'lan1 lan2'```
We only supported the former syntax. This patch add support for the
latter syntax to me more robust.

ss-redir-init: Be more tolerant in uci syntax

---

mwan3otb/Makefile
mwan3otb/files/etc/hotplug.d/iface/16-mwancustom

Use $INTERFACE instead of $DEVICE, sometimes the hotplug call has an
interface name but no device.
Documentation:
https://wiki.openwrt.org/doc/techref/hotplug
INTERFACE   Name of the interface which went up or down (e.g. "wan" or
"ppp0")
DEVICE  Physical device name which interface went up or down (e.g.
"eth0.1" or "br-lan")

mwan3otb: Update hotplug to handle interfaces

---

shadowsocks-libev/Makefile
shadowsocks-libev/files/shadowsocks.hotplug

Reload is needed when :
- mwan3 rules
- static routes
- local WAN interfaces IP
change.
The script in /etc/hotplug.d/net/05-mwan3-post calling reload_config
should do the job, providing the config really changed.

Do not reload shadowsocks on each ifup

---

bandwidth/Makefile
dnsmasq/Makefile
glorytun-udp/Makefile
glorytun/Makefile
luci-app-overthebox/Makefile
luci-base/Makefile
luci-theme-ovh/Makefile
mptcp/Makefile
mwan3otb-luci/Makefile
mwan3otb/Makefile
netifd/Makefile
shadowsocks-libev/Makefile

Package version bumped:
* bandwidth/Makefile
* dnsmasq/Makefile
* glorytun-udp/Makefile
* glorytun/Makefile
* luci-app-overthebox/Makefile
* luci-base/Makefile
* luci-theme-ovh/Makefile
* mptcp/Makefile
* mwan3otb-luci/Makefile
* mwan3otb/Makefile
* netifd/Makefile
* shadowsocks-libev/Makefile
Signed-off-by: Grégoire Delattre <gregoire.delattre@corp.ovh.com>

Bump versions

---

swconfig-otb/Makefile

swconfig-otb: Add dependency python-setuptools

---

overthebox/files/etc/opkg/keys/6bc78405bb9b7cc3
overthebox/files/etc/uci-defaults/otb-key.defaults

Removing the package overthebox should not remove the key.

overthebox: Move OTB build key in uci-defaults

---

overthebox/files/etc/uci-defaults/otb-wireless.defaults

Reload network fails if the wireless config is not present since #493

netifd: Fix reload network

---

overthebox/Makefile

overthebox: Remove bash as it's now useless

---

otb-remote/init
otb-remote/otb-action-remoteAccessDisconnect

remote user public keys are now all in the same and unique valid file
for the root user : /etc/dropbear/authorized_keys

otb-remote: Fix public key location

---

overthebox/files/bin/otb-subscribe

If the device is already linked to a service, don't subscribe again
If we have a device ID and a token, but when we try to retrieve the
config we get a 401, subscribe again

overthebox: Get new device if no service & got 401

---

luci-app-overthebox/luasrc/controller/admin/overthebox.lua

Typo introduced here 06ba2d6d6f18aac21c6fdc3c02d59c8e65a1b7ce
https://w000t.me/066492a738

luci-app-overthebox: Fix typo

---

overthebox/files/usr/share/otb/post-tracking.d/get-ip-asn

Do not write ip if it has'nt changed.
Do not call asn api if ip hasn't changed.

overthebox: Fix get-ip-asn

---

glorytun-udp/Makefile
glorytun-udp/start

When a new interface is added, glorytun is restarted, but the restart
can happen before an IP is set on the interface, and event before the
interface is up
If the interface is not up, let glorytun restart itself 30 seconds
later
Fixes #645 

glorytun-udp: Only start when everybody is ready

---

otb-tracker/bin
otb-tracker/init

Current post_tracking scripts have been tested and concurrency is not a problem.
Make sure next post_tracking scripts can be executed concurrently before integrating them.
Be aware that termination order can not be anticipated.

otb-tracker: Remove timeout from post-tracking

---

overthebox/files/etc/udhcpc.user

When udhcp.user is ran, the IP is already on the interface

overthebox: Fix duplicate ip address check

---

overthebox/Makefile

overthebox: Add missing exec of vfat uci-defaults

---

overthebox/Makefile
overthebox/files/bin/otb-action-sysupgrade

overthebox: gunzip and -p are now useless for sysupgrade

---

otb-autoroute/Makefile
otb-autoroute/bin

Quotes were creating errors : 
```user.notice post-tracking-otb-autoroute: add rule matching 0x7874756e using table 101 and pref 30000
daemon.err otb-tracker[7889]: Error: argument "101 pref 30000" is wrong: invalid table ID
daemon.err otb-tracker[7889]:
```

otb-autoroute: Fix quotes in ip rules

---

overthebox/Makefile
overthebox/files/etc/udhcpc.user

Occured when a dhcp server was giving multiple gateways
Fixes #754

overthebox: Fix infinite wan discovery

---

shadowsocks-libev/Makefile
shadowsocks-libev/files/shadowsocks.init

This allows shadowsocks to always be the last entry in the nat table of
the PREROUTING chain.
Fixes #786

shadowsocks: Reload if the firewall config change

---

overthebox/Makefile
overthebox/files/etc/hotplug.d/net/10-otb-lan
overthebox/files/etc/uci-defaults/1910-otb-network

Clean the changes introduced in d62b39d. Use the network configuration
file to setup the rule instead of a hotplug script.

overthebox: Set the lan rule in the config

---

overthebox/files/bin/otb-status

overthebox: display lines latencies in otb-status

---

shadowsocks-libev/Makefile
shadowsocks-libev/files/shadowsocks.init

TCP traffic for internal needs should go through shadowsocks for the
following URLs:
* downloads.overthebox.net
* provisionning.overthebox.net

shadowsocks-libev: Add output rules

---

overthebox/Makefile
overthebox/files/etc/uci-defaults/1900-firewall

Some users experience hangs while using the port forwarding from the
public IP to a specific web server in the lan. If the web server
response is to big, the OTB will send a ICMP packet to tell it to
defragment the packet. If the web server does not handle this
fragmentation the end user will never receive the data.
Enabling the MSS clamping on the lan will allow both parties to
negotiate the correct MSS and to communicate without fragmentation.

overthebox: Setup MSS clamping in lan

---

overthebox/Makefile
overthebox/files/bin/otb-action-speedtest

Dirty fix edge cases when iperf is not ready to accept new connections
with a sleep
Add option to the script in order to test a specifix interface

overthebox: Better speedtest

---

overthebox/Makefile
overthebox/files/bin/otb-status

This fixes the 'otb-status' command while using LTE modems over ttyUSB
devices.

overthebox: Use the l3 device in otb-status

---

overthebox/files/etc/udhcpc.user

If the client's modem is giving multiple DNS, they may not be setup
correctly in the network and dhcp config
Bump overthebox package while we're here

overthebox: Fix bad DNS discovery

---

overthebox/Makefile
overthebox/files/etc/uci-defaults/1920-otb-qos

If the user hasn't changed its dscp config file, copy the new
configuration

overthebox: Keep the dscp config file up to date

---

swconfig-otb/Makefile

 swconfig-otb: Use full path of python-package.mk 

---

luci-app-overthebox/Makefile
luci-app-overthebox/luasrc/controller/admin/overthebox.lua

This code is checking bandwidth for all kind of interfaces ( including
lan_ifX interfaces that are not really interfaces )
Bump package while we're here

luci-app-overthebox: Don't check length of nil var

---

overthebox/Makefile
overthebox/files/etc/uci-defaults/1920-otb-qos

Bump overthebox package version

overthebox: Fix wrong md5 of dscp config files

---

overthebox/Makefile
overthebox/files/etc/uci-defaults/1910-otb-network

* Remove the old "type macvlan" because it's useless
* Don't force the lan to be a macvlan if it's configured otherwise

overthebox: Update network uci defaults

---

otb-dscp/bin

As the script is set -e , ensure that the returns are 0

otb-dscp: Ensure that bin doesn't exists early

---

overthebox/files/bin/otb-action-configure

overthebox: Don't let jq print null when no error

---

overthebox/files/etc/uci-defaults/1930-otb.defaults

overthebox: Don't start mini_snmpd by default

---

overthebox/Makefile

overthebox: Add missing macvlan from 0.7 backport

---

overthebox/files/bin/otb-action-refreshProperties

overthebox: Enable traffic_control only on wan interfaces

---

overthebox/files/etc/uci-defaults/1940-otb-event

This event will be trigger during the first boot, after a sysupgrade or
after a reset.

overthebox: Add a 'first-setup' event

---

overthebox/files/etc/hotplug.d/iface/90-overthebox
overthebox/files/lib/overthebox

Add an optional argument to otb_save_event to specify the name of the
todo, and by default, choose the name of the event

overthebox: Fix ifup/ifdown events name

---

overthebox/files/bin/otb-action-sysupgrade

Sometimes the download of the image via tun0 (which is the default route
from the device) makes the latency explode and we're then unable to
download the signature, thus interrupting the sysupgrade.
We reverse the order of the downloads to make it less likely to get
connect timeout errors

overthebox: Improve sysupgrade reliability

---

overthebox/files/bin/otb-check-config

Fixed with https://github.com/angt/glorytun/commit/cce55fac2155997dbcad34ca2c9bc53d9e421ccd

overthebox: The use of dd is now useless

---

otb-qos/Makefile
otb-qos/otb-cake-parser

With the new version of tc, the output of "tc -s qdisc show dev if1"
changed, a few lines were added before the actual statistics
This fixes upload QoS graphs

otb-qos: Fix otb-cake-parser

---

overthebox/Makefile
overthebox/files/bin/otb-action-upgrade

To upgrade an OverTheBox device, a sysupgrade is now needed

overthebox: Upgrade is now deprecated

---

overthebox/files/bin/otb-check-config

Checking for the correct table is enough for all cases.

overthebox: Fix bad route detection

---

overthebox/files/bin/otb-action-speedtest

Proposed change loops five times max to handle speedtest timeout when determining upload or download speed

overthebox: loop 5 times max to handle timeouts
