shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.init
=> Shadowsocks: make ss-redir to use all core by launching N instance on the same port

luci-app-overthebox/luasrc/view/overthebox/lan_traffic.htm
=> bandwidth: Fixes bug for pre ES2015/ES6 browsers.

libsodium/Makefile
no CVE but still a good thing to update :)
=> Update libsodium to 1.0.10

mwan3otb/files/usr/sbin/track.lua, overthebox/files/etc/init.d/dscp
- avoid "/etc/init.d/dscp reload" loop with tracker
- Handle Interactive, light and heavy traffic
=> Improve qos 

overthebox/defaults/network.defaults, overthebox/files/etc/init.d/dscp, overthebox/files/etc/init.d/qos, overthebox/files/usr/lib/qos/otb.qos, overthebox/files/usr/lib/qos/run.sh
Allow trackers to start with custom upload and download values
Convert sqm to new interface trafficcontrol (fix #108)
Remove deprecated code
=> Qos bugfix

glorytun-udp/Makefile, glorytun-udp/files/glorytun.init, glorytun-udp/files/glorytun.sh, shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.hotplug, shadowsocks-libev/files/shadowsocks.init
* Wait for the statefile to be removed by the process when the script
stops
* Removed unused vars
Fixes #115
=> Fix race condition in the glorytun-udp service

luci-app-overthebox/luasrc/view/overthebox/multipath.htm
Add overall traffic to multipath view :)
=> Add overall traffic to multipath view :)

overthebox/files/usr/bin/overthebox_emergency_action
- **configure** was not implemented
- **reboot** had a bug
- **sysupgrade** did not inform our infra that the action was done after reboot
=> Fix emergency actions

mwan3otb/files/usr/sbin/track.lua
- ~~Use socket.gettime().~~
- ~~Don't exit when time changes, just skip the metric.~~
- Spaces and tabs cleanup.
- Rename libping to ping.
- Remove unused handle_exit() and hex_dump().
- Use string.find() for match without pattern.
=> Code cleanup of track.lua

overthebox/Makefile, overthebox/defaults/power.defaults, overthebox/files/tmp/overthebox-power-button.sh, overthebox/files/usr/bin/overthebox_download_recovery
- set SquashFS as the default recovery image
- use the overlay to reset to factory if SquashFS is already used
=> Update the recovery scripts / Reset factory

mwan3otb/files/usr/sbin/track.lua
On `149.202.xxx.xxx`:
whois() returns RIPE-ERX-149-201-0-0 (iana refer arin for this ip)
get_asn() returns OVH
=> Use iptoasn.com to get better ASN info

overthebox/Makefile
=> Enable dnsmasq upon overthebox postinst

overthebox/files/etc/init.d/otb-remote
Signed-off-by: Lucas BEE <pouulet@gmail.com>
=> Fix errors when authorized_keys doesn't exist

overthebox/files/usr/lib/lua/overthebox.lua
Add -n option to lsof to avoid dns issues
Signed-off-by: Lucas BEE <pouulet@gmail.com>
=> Add uptime as part of diag

overthebox/files/usr/bin/overtheboxd, overthebox/files/usr/lib/lua/overthebox.lua
Add more logs for clarity
Return the action as an error when one of the step was an error
=> Better check of the upgrade on the system

overthebox/files/usr/bin/overthebox_checkup, overthebox/files/usr/lib/lua/overthebox.lua
Sometimes overtheboxd has zombies, we kill them if needed
But more importantly, we'll never kill anyone else
Now we'll know exactly what we're killing and who is the zombie
=> Only kill the zombies we created

glorytun-udp/Makefile
=> glorytun-udp: Add forgotten bump in 3fee922

overthebox/Makefile
=> Add a call to reload_config after setting defaults

overthebox/files/sbin/overthebox_last_upgrade
=> Delete last traces of ext images

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
Fix tun service is not running warning
=> overview: update glorytun process check

build-packages.sh, overthebox/Makefile, overthebox/files/sbin/overthebox_last_upgrade
=> Remove last traces of trunk

mwan3otb/files/usr/sbin/track.lua
We do not need entry
Fix border case when the buffer should be full
=> Fix the way we use the ping buffer

overthebox/files/usr/lib/lua/overthebox.lua
Read /dev/kmsg buffer file to find kernel build time and mptcp version : 
```
root@sticky:~# lua -e "print(require('overthebox').get_kernel_build_info())"
Linux version 4.1.35 (seb@compile) (gcc version 5.3.0 (OpenWrt GCC 5.3.0 49994) ) #1 SMP Fri Dec 23 11:48:56 UTC 2016	1
root@sticky:~# lua -e "print(require('overthebox').get_mptcp_version())"
MPTCP: Stable release v0.91.2 - 7dc057edb502	1
```
=> OverTheBox: Append kernel and mptcp version to send properties

mwan3otb/files/usr/sbin/track.lua
=> mwan3otb: Log when method() fails

mwan3otb/files/usr/sbin/track.lua
=> mwan3otb: Use socket.gettime()

glorytun-udp/Makefile
=> glorytun-udp: Update to 0.0.84-mud

mwan3otb/files/usr/sbin/track.lua
Introduced in b49ed2928ed50b8b351bfbed7e111f468f8d9cc9
=> mwan3otb: Fix bad unit for time

luci-app-overthebox/Makefile, mwan3otb/Makefile, shadowsocks-libev/Makefile
=> Bump versions

overthebox/defaults/network.defaults, overthebox/files/usr/lib/lua/overthebox.lua
=> overthebox: Update network.tun0 for ptp/mud

glorytun-udp/Makefile
=> glorytun-udp: Update to 0.0.85-mud

mwan3otb/files/usr/sbin/track.lua
=> mwan3otb: Code cleanup

mwan3otb/files/etc/hotplug.d/iface/15-mwan3
=> mwan3otb: Fix iptables to handle fallback

glorytun-udp/Makefile
=> glorytun-udp: Update to 0.0.86-mud

mwan3otb/files/usr/sbin/track.lua
=> mwan3otb: Remove old (and unused) part of the tracker

glorytun-udp/Makefile
=> glorytun-udp: Update to 0.0.87-mud

glorytun-udp/Makefile
=> glorytun-udp: Update to 0.0.88-mud

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Compute a smooth ping

mwan3otb/files/usr/sbin/mwan3
=> mwan3otb: Fix redirect in ifup()

mwan3otb/Makefile, mwan3otb/files/etc/hotplug.d/iface/15-mwan3, mwan3otb/files/etc/hotplug.d/net/05-mwan3-post, overthebox/files/sbin/overthebox_test_download_proof, overthebox/files/usr/lib/lua/overthebox.lua, shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.init
* ~~Bug when calling reload if shadowsocks is stopped~~
* ~~Need to update hotplug script referencing old name -j SOCKS~~
* ~~Need to update /sbin/overthebox_test_download_proof~~
* ~~Make ifup idempotent~~
* ~~Find a way to count CPU cores and not CPU threads~~
* ~~Validate uci config before doing anything~~
* ~~Add EXTRA_HELP~~
* ~~Embed a documentation of the used iptables/ipset layout~~
* ~~Correct spelling mistakes~~
* ~~Remove obsolete tracker parameters (reliability, up, down, count)~~
* ~~Use "." command instead of "source" for compat~~
* ~~Put each member of LOCALNETS on a separated line~~
* ~~Bug when calling ifup/ifdown if shadowsocks is stopped~~
=> Enhance shadowsocks.init robustness

shadowsocks-libev/files/shadowsocks.track
=> shadowsocks-libev: Use a curl based ss-tracker

mwan3otb/files/etc/hotplug.d/iface/16-mwancustom
* Remove the interface on ifdown from MPTCP
* Make the function to add/remove a route idempotent
* Refactoring of the script structure
* Remove all the sleeps in the code
=> mwan3otb: Update the 16-mwancustom hotplug script

glorytun-udp/files/glorytun.init, glorytun/files/glorytun.init
=> glorytun(-udp): Restart on reload_config

luci-app-overthebox/Makefile
Signed-off-by: Grégoire Delattre <gregoire.delattre@corp.ovh.com>
=> Bump luci-app-overthebox version to v1.0.3

mptcp/files/etc/hotplug.d/iface/30-mptcp, mptcp/files/etc/hotplug.d/net/02-tcp_cong, mptcp/files/etc/hotplug.d/net/03-mptcp
Delete useless tcp_cong file while we're here
=> mptcp: Apply shellcheck

luci-mod-admin-full/luasrc/model/cbi/admin_network/network.lua
We can still change the value with sysctl
=> Delete tcp congestion control choice

netifd/files/lib/netifd/dhcp.script
The original part of the code is left unchanged.
=> netifd: Apply shellcheck on dhcp.script

overthebox/defaults/overthebox.defaults
=> overthebox: Use /etc/hosts for api

overthebox/files/usr/bin/overtheboxd, overthebox/files/usr/lib/lua/overthebox.lua
=> overthebox: Update the backup code in lua lib

overthebox/defaults/network.defaults
=> overthebox: Remove tun0 in network.defaults

overthebox/Makefile
=> overthebox: Add graph in DEPENDS

mwan3otb/files/etc/hotplug.d/net/05-mwan3-post, overthebox/Makefile, overthebox/defaults/network.defaults
=> Reload config if /var/run/config.check does not exist

overthebox/defaults/overthebox.defaults
=> overthebox: Kill scollector

overthebox/defaults/overthebox.defaults
=> overthebox: Regenerate cert files in postinstall

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Remove tabs in mwan3track

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Remove bw_stats

mwan3otb/Makefile
Signed-off-by: Grégoire Delattre <gregoire.delattre@corp.ovh.com>
=> mwan3otb: Bump version to 1.7.35

.travis.yml
=> travis: Use transfer.sh instead of plik

glorytun-udp/Makefile, glorytun/Makefile
=> glorytun: Update deps

overthebox/Makefile, overthebox/files/usr/bin/overthebox_emergency_action, overthebox/files/usr/lib/lua/overthebox.lua, sticky/Makefile
=> Add meta-package sticky

vlan/Makefile
=> Add meta-package vlan

glorytun-udp/Makefile
=> glorytun-udp: Fix PKG_BUILD_DIR

swconfig-otb/Makefile
=> swconfig-otb: Add dependency lsof

vlan-bash/Makefile, vlan/Makefile
=> build: Update metapackages

overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults
=> overthebox: Update dnsmasq setup for vlan

swconfig-otb/Makefile
=> swconfig-otb: Move setuptools in PKG_BUILD_DEPENDS

mwan3otb/files/etc/hotplug.d/iface/16-mwancustom
=> mwan3otb: Fix bad argument when calling multipath

bandwidth/files/bandwidth
=> bandwidth: Fix bad device

bandwidth/files/bandwidth
=> bandwidth: Cleanup

netifd/files/lib/netifd/dhcp.script
=> netifd: Cleanup dhcpdiscovery

overthebox/files/usr/lib/lua/overthebox.lua, shadowsocks-libev/files/shadowsocks.init
```
Thu May  4 12:52:12 2017 daemon.err ss-redir[15783]:  2017-05-04 12:52:12 INFO: using tcp fast open
Thu May  4 12:52:12 2017 daemon.err ss-redir[15783]:  2017-05-04 12:52:12 INFO: tcp port reuse enabled
```
=> Add shadowsocks ReUse and FastOpen support

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Fix bad device name

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Fix bad device in get_public_ip()

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Fix bad device name again

sticky/Makefile, vlan-bash/Makefile, vlan/Makefile
=> packages: Add conntrack

shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.init
=> shadowsocks-libev: Update to 3.0.6.1

mwan3otb/files/etc/hotplug.d/iface/15-mwan3
=> mwan3otb: fix iptables length filter on icmp

overthebox/Makefile, sticky/Makefile, vlan-bash/Makefile, vlan/Makefile
=> packages: Move dependencies to overthebox

vlan-bash/Makefile, vlan/Makefile
=> packages: Add python-swconfig-otb only on x86

overthebox/Makefile
=> overthebox: Add kmod-ipt-raw

netifd/files/lib/netifd/dhcp.script
=> netifd: Fix dhcp.script

overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults
=> overthebox: Disable authoritative if if0 exists

bandwidth/files/bandwidth
=> bandwidth: Exit if lan doesn't exist

overthebox/files/etc/uci-defaults/otb-crontab.defaults, overthebox/files/usr/bin/overthebox_download_recovery, overthebox/files/usr/bin/overthebox_emergency_action
Wait before emergency actions
Change the wait before download_recovery
=> Update crontab wait times

overthebox/files/etc/init.d/otb-remote
=> overthebox: Fix otb-remote

overthebox/files/etc/uci-defaults/otb-dscp.defaults, overthebox/files/etc/uci-defaults/otb-firewall.defaults
=> overthebox: Fix uci-defaults

overthebox/files/sbin/overthebox_last_upgrade
=> overthebox: Fix overthebox_last_upgrade

overthebox/files/etc/uci-defaults/otb-firewall.defaults
=> overthebox: Use named zone

glorytun/Makefile
=> glorytun: Update to 0.0.35

overthebox/files/usr/bin/overthebox_mptcp_check
=> overthebox: Use network_get_gateway in mptcp_check

shadowsocks-libev/files/shadowsocks.init
=> shadowsocks-libev: Source network.sh when needed

overthebox/Makefile
=> overthebox: Add command file

overthebox/files/sbin/overthebox_last_upgrade
=> overthebox: Don't select a default image to upgrade

overthebox/Makefile
=> overthebox: Add ip-full

overthebox/Makefile
=> overthebox: Cleanup

overthebox/files/etc/init.d/overtheboxd
=> overthebox: Always respawn overtheboxd

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Check fd as p.socket() can fail

mwan3otb/files/usr/sbin/mwan3track
=> mwan3otb: Fix raw socket support

overthebox/Makefile
=> overthebox: Add iptables-mod-trace

overthebox/files/etc/opkg/keys/6bc78405bb9b7cc3
=> overthebox: Add OTB build key

otb/Makefile
=> Add bmon and bwm-ng

circle.yml
=> build: Add circle.yml

circle.yml
=> build: Overwrite OTB_FEED

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
=> luci-app-overthebox: fix the fix (611f824)

luci-app-overthebox/luasrc/controller/admin/overthebox.lua, overthebox/files/usr/lib/lua/overthebox.lua
=> luci: Fix dhcp_status in overview

jq/Makefile
=> packages: Add jq

overthebox/files/etc/uci-defaults/otb-random.defaults
=> overthebox: Setup rngd

overthebox/files/bin/otb-action-upgrade
=> overthebox: Fix otb-action-upgrade

overthebox/files/bin/otb-action-upgrade
=> overthebox: Force upgrade of all packages

overthebox/files/bin/otb-action-configure
=> overthebox: Configure network (only mud)

mwan3otb/files/etc/hotplug.d/net/05-mwan3-post, overthebox/files/bin/otb-action-configure, overthebox/files/bin/otb-action-upgrade, overthebox/files/bin/otb-daemon
=> Call reload_config at one time

overthebox/files/bin/otb-action-upgrade, overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Cleanup uci-defaults

overthebox/files/bin/otb-action-askServiceConfirmation, overthebox/files/bin/otb-confirm-service, overthebox/files/lib/overthebox
=> overthebox: Update service confirmation

jq/Makefile
=> jq: Update Makefile

dnsmasq/Makefile, dnsmasq/patches/010-Tweak-ICMP-ping-check-logic-for-DHCPv4.patch, dnsmasq/patches/020-Try-other-servers-if-first-returns-REFUSED-when-stri.patch
=> dnsmasq: Bump version to 2.77-5

overthebox/files/usr/lib/lua/overthebox.lua
=> overthebox: stun0 doesn't exists

luci-app-overthebox/luasrc/view/overthebox/activate.htm, luci-app-overthebox/luasrc/view/overthebox/dhcpwizard.htm, luci-app-overthebox/luasrc/view/overthebox/index.htm, luci-app-overthebox/luasrc/view/overthebox/ipv6wizard.htm, luci-app-overthebox/luasrc/view/overthebox/register.htm
index.htm includes other htm file that all load cbi.js.
Now we load cbi.js earlier with the index.htm
=> luci-app-overthebox: fix String.format not a function

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
=> luci-app-overthebox: Remove action_update_conf()

graph/Makefile, graph/bin, graph/init
=> graph: Don't use procd as main loop

glorytun-udp/init
=> glorytun-udp: Force stop/start on reload

overthebox/files/bin/otb-action-configure
=> overthebox: Fix glorytun_hybrid conf

overthebox/files/etc/uci-defaults/otb-network.defaults, overthebox/files/etc/udhcpc.user
=> overthebox: Add lan_if for dhcp static lease

otb/Makefile
=> otb: Fix otb-x deps

overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults, overthebox/files/etc/udhcpc.user
=> overthebox: Force dhcp.force=1 for luci

dnsmasq/Makefile, dnsmasq/files/dnsmasq.init
=> dnsmasq: Update to 2.77-7

swconfig-otb/Makefile, swconfig-otb/files/swconfig-wan.sh
=> swconfig-otb: Add swconfig-wan.sh

overthebox/files/etc/uci-defaults/1900-otb-network
=> overthebox: Fix 1900-otb-network

overthebox/files/etc/uci-defaults/1900-firewall, overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults, overthebox/files/etc/uci-defaults/otb-random.defaults, overthebox/files/etc/uci-defaults/otb-ucitrack.defaults, overthebox/files/etc/uci-defaults/otb-uhttpd.defaults, overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Remove all commits in uci-defaults

swconfig-otb/files/swconfig-reset
=> swconfig-otb: Rename and fix swconfig-wan.sh

swconfig-otb/Makefile
=> swconfig-otb: Fix install

overthebox/files/lib/overthebox
=> overthebox: Fix otb_save_event() on ash

circle.yml
=> circleci: Add OTB_VERSION

overthebox/files/bin/otb-action-configure, overthebox/files/etc/uci-defaults/1910-otb-network, swconfig-otb/files/swconfig-reset
=> overthebox: fix add_list, don't add things more than once

otb-diagnostics/Makefile, otb/Makefile, overthebox/Makefile
https://github.com/openwrt/packages/blob/lede-17.01/utils/dmidecode/Makefile#L29
=> overthebox: set dmidecode to x86 targets only

otb-remote/otb-action-remoteAccessConnect, otb-remote/otb-action-remoteAccessPrepare
=> otb-remote: Check for null value from jq

overthebox/files/bin/otb-daemon
=> overthebox: Check and exit for null action

circle.yml
=> circleci: Build tags

overthebox/files/bin/otb-action-sysupgrade
=> overthebox: Download latest-uefi.img.gz on uefi

svfs/Makefile
=> svfs: Update to 0.9.1 and cleanup

circle.yml
=> circleci: Use overthebox v2.2

otb-tracker/Makefile, otb-tracker/bin, otb-tracker/init
Signed-off-by: Kevin Lanvin <info.lanvink@gmail.com>
=> otb-tracker: Fix command line arguments

overthebox/files/bin/otb-tracker-interfaces, overthebox/files/usr/share/otb/post-tracking.d/store_state
Signed-off-by: Kevin Lanvin <info.lanvink@gmail.com>
=> overthebox: Add otb-tracker-interfaces command

otb/Makefile
=> otb: Don't use wildcard in DEPENDS

jq/Makefile
=> jq: Move package to Base system

luci-app-overthebox/luasrc/controller/admin/overthebox.lua, luci-app-overthebox/luasrc/view/overthebox/wanstatus.htm
=> luci-app-overthebox: Don't use mwan3 to get wans

otb-qos/Makefile, otb/Makefile, overthebox/Makefile
=> packages: Update dependencies

luci-app-overthebox/luasrc/view/overthebox/wanstatus.htm
=> luci-app-overthebox: Don't show disabled/invalid tc

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
=> luci-app-overthebox: Fix whois when curl fails

overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Force remove mwan3otb

overthebox/files/bin/otb-tracker-interfaces
=> overthebox: Beautify otb-tracker-interfaces

shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.init
=> shadowsocks-libev: Remove old mwan3 code

overthebox/files/bin/otb-action-configure
=> overthebox: Remove useless mwan3.socks.dest_ip

overthebox/files/bin/otb-daemon, overthebox/files/lib/overthebox
=> overthebox: Add call-api methods

overthebox/files/bin/otb-action-configure
=> overthebox: Cleanup config on otb-action-configure

otb-tracker/bin
=> otb-tracker: Check for args

otb-qos/files/etc/init.d/qos
=> otb-qos: Restore api calls

circle.yml
=> circleci: Use overthebox v2.3

overthebox/files/bin/otb-action-upgrade
=> overthebox: otb-action-upgrade should only upgrade

overthebox/files/bin/otb-action-sysupgrade
=> overthebox: Allow url/json argument in otb-action-sysupgrade

luci-mod-admin-full/luasrc/controller/admin/system.lua
=> luci-mod-admin-full: Allow action_reset()

otb-remote/Makefile, otb-remote/otb-action-remoteAccessDisconnect
=> otb-remote: Delete public key only if file exists

otb-qos/files/usr/share/otb/post-tracking.d/qos
=> otb-qos: Add log and fix device/interface name

overthebox/files/usr/share/otb/post-tracking.d/get-ip-asn
=> otb-tracker: Fix get-ip-asn

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
=> luci-app-overthebox: Hide if0 in the overview

otb-remote/init
=> otb-remote: Remove old useless chmod

otb-remote/init
=> otb-remote: chmod 600 for dropbear/authorized_keys

overthebox/files/lib/overthebox
=> overthebox: Fix timestamp in otb-events

luci-app-overthebox/luasrc/controller/admin/overthebox.lua
=> luci-app-overthebox: Fix overview when asn is nil

overthebox/files/bin/otb-action-speedtest
Stops and starts the new otb-qos service
=> overthebox: Fix speedtest

overthebox/files/bin/otb-action-restartServices
Take a list of services and restart them
=> overthebox: Add action restartServices

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/controller/admin/overthebox.lua, otb-qos/Makefile, otb-qos/otb-cake-parser
To complete #620 and close #497
=> Add Cake graph

circle.yml, otb-full/Makefile, otb/Makefile
Requires ovh/overthebox#102 to work
=> otb: Add optional deps in a separate metapackage

overthebox/Makefile, overthebox/files/bin/otb-action-configure
=> overthebox: Change tunnel tracking policy

otb/Makefile
=> otb: Remove kmod-fs

shadowsocks-libev/files/shadowsocks.init
=> shadowsocks: Fix the detection of the CPU count

overthebox/files/bin/otb-action-updateReleaseChannel
=> overthebox: Add arch/board support in updateReleaseChannel

otb-full/Makefile
=> packages: Add (optional) netdata package

overthebox/Makefile, overthebox/defaults/vfat.defaults
=> Add vfat.defaults and bump to 0.5.4

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/controller/admin/overthebox.lua, luci-app-overthebox/luasrc/view/overthebox/add_interface.htm, luci-mod-admin-full/Makefile, luci-mod-admin-full/luasrc/view/admin_network/iface_overview.htm, overthebox/Makefile, overthebox/files/etc/udhcpc.user
Adds an OTB interface manually and have all the right config ( macvlan +
ip4table )
=> Add page to add interface

overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Set ttylogin

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/view/overthebox/index.htm, luci-app-overthebox/luasrc/view/overthebox/register_device.htm
=> luci-app-overthebox: Change wizard for v2

overthebox/Makefile, overthebox/files/etc/uci-defaults/otb-tracker.defaults
=> ovethebox: Add uci-defaults for otb-tracker

luci-app-overthebox/htdocs/luci-static/resources/view_scripts/nuc.js
=> luci-app-overthebox: Fix fucked up wizard

overthebox/files/bin/otb-action-reboot, overthebox/files/bin/otb-action-sysupgrade, overthebox/files/bin/otb-daemon, overthebox/files/lib/overthebox
=> overthebox: Save and send action_id on reboot/sysupgrade

overthebox/files/lib/overthebox
=> overthebox: Prettify otb_pretty_print()

overthebox/Makefile, overthebox/files/bin/otb-action-refreshProperties
=> overthebox: Cleanup action refreshProperties

otb-diagnostics/Makefile, otb-diagnostics/diags/opkg-list-installed
=> otb-diagnostics: Add opkg-list-installed

overthebox/files/bin/otb-action-upgrade
=> overthebox: Refuse upgrading when base-files has changed

overthebox/Makefile, overthebox/files/bin/otb-daemon, overthebox/files/bin/otb-subscribe, overthebox/files/lib/overthebox
=> overthebox: Rework subscribe

overthebox/Makefile, overthebox/files/bin/otb-daemon
=> overthebox: Force a refreshProperties at start

overthebox/Makefile, overthebox/files/bin/otb-action-sysupgrade, overthebox/files/lib/overthebox
By the way, let's add some logs
=> overthebox: Allow sysupgrade without args

luci-app-overthebox/luasrc/view/overthebox/multipath.htm
=> luci-app-overthebox: Patch for graphs

overthebox/files/bin/otb-status
=> overthebox: Add more options to otb-status

otb-full/Makefile
=> otb-full: Add iputils-ping

circle.yml
=> circleci: Update build to allow all kmods

otb-full/Makefile
=> otb-full: Add perf

otb-full/Makefile, otb/Makefile
=> packages: Move bmon in otb-full

dnsmasq/Makefile, dnsmasq/files/dnsmasq.init, dnsmasq/files/dnsmasq_acl.json, dnsmasq/patches/011-Remove-ping-check-of-configured-DHCP-address.patch, dnsmasq/patches/025-fix-CVE-2017-13704.patch, dnsmasq/patches/240-ubus.patch
=> dnsmasq: Update to 2.77-10

otb-full/Makefile, otb/Makefile
=> packages: Move ethtool in otb-full

overthebox/Makefile, overthebox/files/bin/otb-daemon
=> overthebox: Fix resubscribe

overthebox/files/usr/share/otb/post-tracking.d/get-ip-asn
=> overthebox: Fix pub_ip retrieving

overthebox/Makefile, overthebox/files/bin/otb-subscribe
=> Use all static IPs in otb-subscribe

overthebox/Makefile, overthebox/defaults/distupgrade.defaults
This helps remove unwanted files from the configuration backup
=> overthebox: Add a distupgrade uci-defaults

circle.yml
=> circleci: Use overthebox v2.8

overthebox/Makefile
=> overthebox: Use a threaded resolver for curl

otb-tracker/Makefile, otb-tracker/bin, otb-tracker/config, otb-tracker/init, otb-tracker/trackers.d/dns
This can be replaced by checking if the result is a valid ip address, but it is not needed yet.
Fixes issue #710 
=> otb-tracker: Check if dig answer is ok

otb-tracker/Makefile, otb-tracker/bin, otb-tracker/init
=> otb-tracker: Use +dscp of dig

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Fix upgrade

overthebox/files/bin/otb-action-upgrade
=> overthebox: Force overwrite on upgrade

otb-full/Makefile, otb/Makefile
=> packages: Move libimobiledevice and usbmuxd to otb

otb-full/Makefile
=> otb-full: Add openvpn

overthebox/Makefile, overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults
=> overthebox: Update dhcp config before tags

otb/Makefile
=> otb: Bump to 0.6.5

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Don't use xargs in otb-action-upgrade

otb-tracker/Makefile, otb-tracker/bin, otb-tracker/init
=> otb-tracker: Fix log spamming

otb/Makefile
=> Bump to 0.6.6

circle.yml
=> circleci: Use overthebox v2.10

otb-diagnostics/Makefile, otb-diagnostics/diags/lsblk
=> otb-diagnostics: Add lsblk

overthebox/Makefile, overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Rename old interfaces to ifX

otb/Makefile
=> otb: Bump to 0.6.7

circle.yml
=> circleci: Use overthebox to v2.11

otb-diagnostics/Makefile, otb-diagnostics/diags/lsblk
=> otb-diagnostics: Show all columns in lsblk

overthebox/Makefile, overthebox/files/bin/otb-action-sysupgrade
=> overthebox: Refuse sysupgrade on bad /proc/cmdline

otb/Makefile
=> otb: Bump to 0.6-11

circle.yml
=> circleci: Use overthebox v2.12

otb-full/Makefile
=> otb-full: Fix typo

overthebox/files/bin/otb-action-askServiceConfirmation, overthebox/files/bin/otb-action-configure, overthebox/files/bin/otb-action-restartServices, overthebox/files/bin/otb-action-speedtest, overthebox/files/bin/otb-action-wait, overthebox/files/bin/otb-confirm-service, overthebox/files/etc/hotplug.d/iface/90-overthebox, overthebox/files/etc/uci-defaults/1900-firewall, overthebox/files/etc/uci-defaults/1910-otb-network, overthebox/files/etc/uci-defaults/otb-config.defaults, overthebox/files/etc/uci-defaults/otb-crontab.defaults, overthebox/files/etc/uci-defaults/otb-dnsmasq.defaults, overthebox/files/etc/uci-defaults/otb-random.defaults, overthebox/files/etc/uci-defaults/otb-wireless.defaults, overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Shellcheckify

overthebox/Makefile, overthebox/files/etc/hotplug.d/net/10-otb-lan, overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Add a specific routing table for LAN

bandwidth/files/bandwidth
Here is the resulting page showing 10.X VLANs machines traffic :
=> Add VLANs interfaces to have IPs appearing in LAN Traffic view

bandwidth/Makefile, bandwidth/files/bandwidth
=> bandwidth: Cleanup and bump to 0.7-1

otb-autoroute/Makefile, otb-autoroute/bin
=> otb-autoroute: Set a pref for the high priority rule

otb-full/Makefile
=> otb-full: Add gdb

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/view/overthebox/index.htm
=> luci-app-overthebox: Fix Gateway Dhcp icon

otb/Makefile
=> otb: Bump to 0.6-12

otb-diagnostics/Makefile, otb-diagnostics/diags/inittab
=> otb-diagnostics: Add inittab

overthebox/files/bin/otb-action-upgrade
=> overthebox: Download all pkgs before upgrading

overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Update network defaults

bandwidth/Makefile, bandwidth/files/bandwidth, bandwidth/files/bandwidth.init
* Get lan interfaces form the firewall.
* Simplify the code.
=> bandwidth: Bump to 0.8

overthebox/Makefile
=> overthebox: Bump to 0.39-1

luci-app-overthebox/htdocs/luci-static/resources/view_scripts/switch/switch_config.js
=> luci-app-overthebox: Fix port index in switch view

luci-app-overthebox/Makefile, luci-app-overthebox/htdocs/luci-static/resources/view_scripts/switch/switch_config.js, luci-mod-admin-full/Makefile, luci-mod-admin-full/luasrc/view/admin_network/switch_status_simple.htm, luci-theme-ovh/Makefile, luci-theme-ovh/htdocs/luci-static/resources/ovh/css/switch-config.css
=> otb-ui: Show tagged ports in switch simple ui

otb/Makefile
=> otb: Bump to 0.6-13

overthebox/Makefile, overthebox/files/bin/otb-action-refreshProperties
And Bump overthebox while we're here
=> overthebox: Add AS & device in refresh properties

circle.yml
=> circleci: Use overthebox v3.0

bandwidth/init
=> bandwidth: Fix Makefile

bandwidth/Makefile
=> bandwidth: Bump to 0.10-1

bandwidth/Makefile, bandwidth/bin
=> bandwidth: Fix arp_populate_iptables()

otb/Makefile
=> otb: Bump to 0.6-14

cherrytrail-gpio-powerbutton/Makefile, cherrytrail-gpio-powerbutton/src/Makefile, cherrytrail-gpio-powerbutton/src/cherrytrail-gpio-powerbutton.c, otb/Makefile
=> packages: Add cherrytrail-gpio-powerbutton

otb/Makefile
=> otb: Bump to 0.6-15

shadowsocks-libev/Makefile, shadowsocks-libev/patches/010-ECONNRESET.patch
=> shadowsocks-libev: Remove 'server recv: Connection reset by peer' log

glorytun-udp/Makefile, glorytun-udp/init, overthebox/Makefile, overthebox/files/bin/otb-action-configure
=> Add option mtu_auto

otb-tracker/Makefile, otb-tracker/bin
=> otb-tracker: Get RTT from Query time

otb-full/Makefile
=> otb-full: Remove perf

otb/Makefile
=> otb: Bump to 0.6-16

circle.yml
=> circleci: Use overthebox v3.3

openssl/Makefile, openssl/patches/150-no_engines.patch
=> openssl: Update to 1.0.2m-1

shadowsocks-libev/Makefile, shadowsocks-libev/files/shadowsocks.init
We need to find a better solution, but this will do the trick
Fixes #715
=> shadowsocks: (Quick)fix the LAN redirection

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/model/cbi/dscp/dscp.lua, luci-app-overthebox/luasrc/view/overthebox/qos.htm, otb-dscp/Makefile, otb-dscp/config, otb-dscp/init, overthebox/files/etc/uci-defaults/1920-otb-qos
=> Rework the DSCP / QoS configuration

otb/Makefile
=> otb: Bump to 0.6.17

overthebox/Makefile
=> overthebox: Bump to 0.44-1

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Refuse upgrade if base-files has changed

otb-dscp/Makefile, otb-dscp/init, otb-qos/Makefile, otb-qos/bin, otb-qos/init, overthebox/Makefile, overthebox/files/lib/overthebox, overthebox/files/usr/share/otb/post-tracking.d/get-ip-asn
=> Qos restart

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Fix bad awk if logic in upgrade

otb/Makefile
=> otb: Bump to 0.6-18

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Rewrite distfeeds on non develop channels

overthebox/Makefile, overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Update vlan config

overthebox/Makefile, overthebox/files/bin/otb-daemon, overthebox/files/etc/init.d/overthebox
=> overthebox: Always try to close correctly

overthebox/files/bin/otb-action-upgrade
=> overthebox: Force reinstall on action upgrade

overthebox/Makefile, overthebox/files/etc/uci-defaults/otb.defaults
=> overthebox: Add provisioning in /etc/hosts

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/controller/admin/overthebox.lua, luci-app-overthebox/luasrc/view/overthebox/wanstatus.htm
Fix bad router values
Show real address
Bump luci-app-overthebox version
=> luci-app-overthebox: Fix lan info on overview

overthebox/files/etc/uci-defaults/otb.defaults
=> Force EOL when updating /etc/hosts

shadowsocks-libev/Makefile, shadowsocks-libev/patches/010-ECONNRESET.patch
=> shadowsocks-libev: Update to 3.1.2-8

otb/Makefile
=> otb: Bump to 0.6-19

overthebox/Makefile, overthebox/files/bin/otb-action-upgrade
=> overthebox: Do a safer upgrade

otb/Makefile
=> otb: Bump to 0.6-20

luci-app-overthebox/Makefile, luci-app-overthebox/luasrc/controller/admin/overthebox.lua
Fixes issue #883
Bumb package while we're here
=> luci-app-overthebox: Fix graph when device is down

otb/Makefile
=> Add LTE packages

.circleci/config.yml
=> circleci: Use overthebox v3.5

overthebox/Makefile, overthebox/files/etc/uci-defaults/1900-firewall
=> overthebox: Fix old "GRE" firewall rules

.circleci/config.yml
=> circleci: Use overthebox v3.6

graph/Makefile, graph/init
=> graph: Cleanup to pass shellcheck

overthebox/files/bin/otb-action-configure
=> overthebox: Fix otb-action-configure

otb-luci/files/usr/lib/lua/luci/controller/glorytun.lua, otb-luci/files/usr/lib/lua/luci/view/otb_overview.htm
=> otb-luci: Show glorytun path in luci

otb-luci/files/usr/lib/lua/luci/view/otb_overview.htm
=> otb-luci: Always print network bit rate with 1000x prefixes

overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Cleanup uci-defaults/1910-otb-network

otb-luci/files/usr/lib/lua/luci/controller/overthebox.lua
=> otb-luci: Code cleanup

overthebox/files/lib/overthebox
=> overthebox: Make sure config/overthebox exists

overthebox/Makefile
=> overthebox: Bump to 0.65

.circleci/config.yml
=> circleci: Use overthebox v4.1

overthebox/files/etc/uci-defaults/1920-otb-0.6-to-0.7
=> overthebox: Improves the migration script 1920-otb-0.6-to-0.7

overthebox/files/etc/udhcpc.user
=> overthebox: Fix lan_ifX with br-lan

otb/Makefile
=> otb: Add kmod-macvlan

overthebox/files/bin/otb-action-configure, overthebox/files/bin/otb-action-refreshProperties
=> overthebox: Skip configure and refreshProperties when no service

overthebox/files/bin/otb-action-reboot, overthebox/files/bin/otb-action-sysupgrade, overthebox/files/bin/otb-daemon, overthebox/files/lib/overthebox
=> overthebox: Let the server handle sysupgrade and reboot status

overthebox/files/bin/otb-subscribe
=> overthebox: Add eth0's macaddr in subscribe

overthebox/files/etc/udhcpc.user
=> overthebox: Log when we change the ip of a dhcp interface

overthebox/files/etc/uci-defaults/1900-firewall
=> overthebox: Don't mask private ip

overthebox/files/etc/uci-defaults/1920-otb-0.6-to-0.7
=> overthebox: Force lan as bridge

otb-diagnostics/diags/otb-status
=> otb-diagnostics: Fix diag otb-status

overthebox/Makefile, overthebox/files/bin/otb-action-configure
=> overthebox: Add bird4 and its conf

otb-diagnostics/Makefile, otb/Makefile, overthebox/Makefile
=> build: Cleanup deps

overthebox/files/bin/otb-check-config
=> overthebox: Install usable routes only

otb-luci/files/etc/uci-defaults/1950-luci, overthebox/files/etc/uci-defaults/1930-otb.defaults
=> Clean luci caches

otb-diagnostics/diags/sysctl
=> otb-diagnostics: Add diag sysctl -a

otb/Makefile
=> otb: Remove debug dependency

.circleci/config.yml
=> circleci: Use overthebox v4.5

.circleci/config.yml
=> circleci: Use overthebox v4.6

overthebox/Makefile
=> overthebox: Add kexec

overthebox/files/lib/overthebox
=> overthebox: Let the provisioning work without DNS

.circleci/config.yml
=> circleci: Use overthebox v4.7

otb-tracker/bin
=> otb-tracker: Update glorytun path

otb/Makefile
=> otb: Remove babeld

otb/Makefile
=> otb: Use dnsmasq

.circleci/config.yml
=> circleci: Use overthebox v4.8

overthebox/files/bin/otb-daemon
=> overthebox: Wait for OTB_SERVICE_ID

otb-luci/files/usr/lib/lua/luci/controller/glorytun.lua, otb-luci/files/usr/lib/lua/luci/view/otb_overview.htm
=> otb-luci: Update overview for glorytun 0.1.x

otb-tracker/Makefile, otb-tracker/bin, otb-tracker/init
=> otb-tracker: Update to use glorytun 0.1.x

glorytun/Makefile, glorytun/init
=> glorytun: Bump to 0.1.0

otb-tracker/bin
=> otb-tracker: Mute glorytun sync

otb-remote/init, otb-remote/otb-action-remoteAccessConnect, otb-remote/otb-action-remoteAccessDisconnect, otb-remote/otb-action-remoteAccessPrepare
=> otb-remote: Cleanup and small fixes

overthebox/files/etc/uci-defaults/1900-firewall
=> overthebox: Don't mask local otb public ip

overthebox/files/etc/sysctl.d/default.conf, overthebox/files/etc/sysctl.d/ipv6default.conf, overthebox/files/etc/sysctl.d/shadowsocks.conf
=> overthebox: Update sysctl

overthebox/Makefile
=> overthebox: Bump to 0.66

otb/Makefile
=> otb: Bump to 0.6-26

overthebox/Makefile
=> overthebox: Restore /etc/config/overthebox

overthebox/Makefile
=> overthebox: Bump to 0.67

otb/Makefile
=> otb: Bump to 0.6-27

otb-luci/files/usr/lib/lua/luci/view/otb_overview.htm
=> otb-luci: Responsive tables

glorytun/Makefile
=> glorytun: Bump to 0.1.1

overthebox/files/bin/otb-action-configure, overthebox/files/bin/otb-check-config, overthebox/files/bin/otb-configure-glorytun, overthebox/files/etc/uci-defaults/1900-firewall, overthebox/files/etc/uci-defaults/1910-otb-network
=> overthebox: Add a firewall zone for tun

overthebox/files/etc/uci-defaults/1900-firewall
=> overthebox: Remove old nat exception

overthebox/files/bin/otb-action-configure, overthebox/files/bin/otb-configure-glorytun
=> overthebox: Accept all packets from our tunnel

.circleci/config.yml
=> circleci: Use overthebox v4.9

otb-dscp/bin, overthebox/files/etc/hotplug.d/iface/90-overthebox, overthebox/files/lib/overthebox
otb-dscp: Change name of event + cleanup
overthebox: Change the name of the todo net event
overthebox: Add function to clean waiting todos
=> Keep some todo

overthebox/files/bin/otb-daemon
- With or without a service, we always come and check if we have actions
to do
- We try to do a resubscribe only if we don't already have a service ID
=> overthebox: Fix otb-daemon

glorytun/Makefile
=> glorytun: Bump to 0.1.2

overthebox/files/bin/otb-check-config
=> overthebox: Delete old paths automatically

otb-diagnostics/diags/otb-status
=> otb-diagnostics: Show glorytun version in otb-status

glorytun/Makefile
=> glorytun: Bump to 0.1.3

glorytun/Makefile
=> glorytun: Bump to 0.2.0

overthebox/Makefile
=> overthebox: Add cake

otb-tracker/bin
- Don't ping tun0 if status is not OK.
- Don't ping interfaces if tun0 pings.
- Retry iptoasn every turn.
- Do // iptoasn.
=> otb-tracker: Improve tracker

overthebox/files/bin/otb-check-config, overthebox/files/bin/otb-daemon
=> overthebox: Improve otb-check-config

overthebox/files/etc/uci-defaults/1920-otb-0.6-to-0.7
=> overthebox: Reconfigure after migration

overthebox/files/bin/otb-action-wait, overthebox/files/bin/otb-daemon
=> overthebox: Handle wait in otb-daemon

overthebox/Makefile, overthebox/files/bin/otb-action-configure, overthebox/files/etc/uci-defaults/1900-firewall, overthebox/files/etc/uci-defaults/1910-otb-network
This PR adds a `tun` firewall zone and forces the device to reconfigure after an update.
=> Add a "tun" firewall zone

overthebox/files/etc/uci-defaults/1900-firewall
=> overthebox: Add missing tun->lan forwarding

glorytun/Makefile
=> glorytun: Bump to 0.2.2

otb-tracker/bin
=> otb-tracker: Ping with diffserv 46 (EF)

otb-luci/files/usr/lib/lua/luci/controller/glorytun.lua
la ligne 16 est rate_rx et la ligne 18 total rx
=> Correction affichage Max Download

otb-luci/files/usr/lib/lua/luci/controller/overthebox.lua, otb-luci/files/usr/lib/lua/luci/view/otb_overview.htm
Add DHCPv6 Leases on OTB Overview
=> DHCPv6 Leases on OTB overview

glorytun/Makefile
=> glorytun: Fix hash

overthebox/files/etc/uci-defaults/1930-otb.defaults
=> overthebox: Cleanup 1930-otb.defaults

glorytun/Makefile
=> glorytun: Bump to 0.3.2

otb-tracker/bin, otb/Makefile
=> otb-tracker: Try 3 pings in 5 seconds

overthebox/files/lib/overthebox
=> overthebox: Remove old otb_call_api()

overthebox/files/bin/otb-check-config
=> overthebox: Enable backup

glorytun/Makefile
=> glorytun: Bump to 0.3.4
